const https = require('https');
const fs = require('fs');

const SHOP = '5iib0q-9y.myshopify.com';
const TOKEN = fs.readFileSync('/home/acharya-kln/.openclaw/workspace/shopify_access_token.txt', 'utf8').trim();
const THEME_ID = 182982246700;

// The standard Judge.me core snippet code
const coreSnippet = `{% comment %} Please do not edit this file. It is automatically updated by Judge.me{% endcomment %}
{% if content_for_header contains 'judgeme' %}
  <script data-cfasync="false" class="jdgm-script">
    !function(e){window.jdgm=window.jdgm||{},jdgm.SHOP_DOMAIN="{{ shop.permanent_domain }}",jdgm.PLATFORM="shopify",jdgm.PUBLIC_TOKEN="TzOofGZ7f0Z9K1-Q9iO4fHq-NFI";}(window);
  </script>
  <script data-cfasync="false" async src="https://cdn.judge.me/widget_preloader.js"></script>
  {{ 'judgeme_widgets.css' | asset_url | stylesheet_tag }}
{% endif %}`;

function uploadAsset(key, value) {
  let putData = JSON.stringify({ asset: { key: key, value: value } });
  let req = https.request({
    hostname: SHOP,
    path: '/admin/api/2024-01/themes/' + THEME_ID + '/assets.json',
    method: 'PUT',
    headers: { 'X-Shopify-Access-Token': TOKEN, 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(putData) }
  }, res => {
    let body = '';
    res.on('data', c => body += c);
    res.on('end', () => console.log('Created snippet:', key));
  });
  req.write(putData);
  req.end();
}

uploadAsset('snippets/judgeme_core.liquid', coreSnippet);